name = "{{name}}"
main = "src/index.ts"
compatibility_date = "2024-06-25"

# Development environment (uses .dev.vars file)

[env.staging]
name = "{{name}}-staging"
# Add staging environment variables here
# vars = { EXAMPLE_VAR = "staging-value" }

[env.production]
name = "{{name}}-prod"
# Production secrets should be set via wrangler secret
# wrangler secret put SECRET_NAME --env production